[[tcp_services]]
name = "http-gateway"
provider = "http"
config = "file://examples/config/tcp/http-gateway.toml"
binds = [
    "[::]:80",
    "[::]:443, tls=switchboard.io"
]

[[tls]]
name = "single-example"
cert_path = "examples/config/tls/single.crt"
key_path = "examples/config/tls/single.key"

[[tls]]
name = "sni-example"
    [[tls.sni]]
    domain = "a.example.com"
    cert_path = "examples/config/tls/sni-a.crt"
    key_path = "examples/config/tls/sni-a.key"
    [[tls.sni]]
    domain = "b.example.com"
    cert_path = "examples/config/tls/sni-b.crt"
    key_path = "examples/config/tls/sni-b.key"