[[tcp_services]]
name = "http-gateway"
provider = "http"
config = "/etc/switchboard/tcp/http-gateway.toml"

[[tcp_listeners]]
bind = "[::]:80"
service = "http-gateway"

[[tcp_listeners]]
bind = "[::]:443"
service = "http-gateway"
tls = "switchboard.io"

[[tls]]
name = "switchboard.io"
cert_path = "/etc/switchboard/tls/switchboard.io/cert.pem"
key_path = "/etc/switchboard/tls/switchboard.io/key.pem"