[[tcp_services]]
name = "http-gateway"
provider = "http"
config = "file://examples/config/tcp/http-gateway.toml"
binds = [
    "127.0.0.1:8080",
    "[::1]:8443, tls=single-example",
    "[::1]:8444, tls=sni-example"
]

[[tcp_services]]
name = "ssh-port-forward"
provider = "pf"
config = "127.0.0.1:22"
binds = [
    "[::]:10022"
]



[[tls]]
name = "single-example"
cert = "file://examples/config/tls/single.crt"
key = "file://examples/config/tls/single.key"

[[tls]]
name = "sni-example"
    [[tls.sni]]
    domain = "sni-a.test.local"
    cert = "file://examples/config/tls/sni-a.crt"
    key = "file://examples/config/tls/sni-a.key"
    [[tls.sni]]
    domain = "sni-b.test.local"
    cert = "file://examples/config/tls/sni-b.crt"
    key = "file://examples/config/tls/sni-b.key"