[info]
name = "Switchboard Kernel"
id = "default"
description = "Default Switchboard Kernel Configuration"

[controller]
psk = "w4Zt3v1+2b5v8y9x0a1b2c3d4e5f6g7h"
[controller.listen.uds]
path = "./tmp/run/kernel/default.sock"
# [controller.listen.tcp]


[startup]
enabled = ["ssh-pf"]

[[startup.named_services]]
name = "ssh-pf"
provider = "tf"
config = "[::1]:22"

[[startup.binds]]
name = "ssh-pf-bind"
addr = "[::]:10022"
service = "@ssh-pf"

