[info]
name = "My Controller"
description = "This is my controller"

[kernel.discovery.uds]
dir = "./tmp/run/kernel/"

[interface.http]

[resolve.fs]
path = "./examples/config/config.toml"

[resource.gateway.k8s]
gateway_namespace = "default"

[storage]
type = "local"
db_file = "./tmp/data/controller_storage.db"