config = "examples/config/config.toml"

[info]
name = "Switchboard Kernel"
id = "default"
description = "Default Switchboard Kernel Configuration"

[controller]
psk = "w4Zt3v1+2b5v8y9x0a1b2c3d4e5f6g7h"
[controller.listen.uds]
path = "./tmp/run/kernel/default.sock"
[controller.listen.http]

